
--FUNCTION GET_CURRENT_EMP_ID 
create or replace FUNCTION GET_CURRENT_EMP_ID RETURN NUMBER IS
    v_emp_id APP_USER.EMP_ID%TYPE;
BEGIN
    SELECT EMP_ID INTO v_emp_id
    FROM   APP_USER
    WHERE  UPPER(USER_NAME) = UPPER(V('APP_USER'));
    RETURN v_emp_id;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/

--FUNCTION GET_CURRENT_USER_ROLE 

create or replace FUNCTION GET_CURRENT_USER_ROLE RETURN VARCHAR2 IS
    v_role APP_USER.ROLE%TYPE;
BEGIN
    SELECT ROLE INTO v_role
    FROM   APP_USER
    WHERE  UPPER(USER_NAME) = UPPER(V('APP_USER'));
    RETURN v_role;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/