--indexes
  CREATE UNIQUE INDEX "APP_USER_CON" ON "APP_USER" ("USER_NAME", "PWD") 
  ;
  CREATE INDEX "EMPID_LEAVE_IDX" ON "LEAVE_REQUESTS" ("EMP_ID") 
  ;
  CREATE INDEX "EMP_DEPT_IDX" ON "EMPLOYEES" ("DEPT_ID") 
  ;  
  CREATE UNIQUE INDEX "PK_AUDIT_ID" ON "LEAVE_AUDIT" ("AUDIT_ID") 
  ;
    CREATE INDEX "REQID_AUDIT_IDX" ON "LEAVE_AUDIT" ("REQUEST_ID") 
  ;
  CREATE INDEX "STATUS_LEAVE_IDX" ON "LEAVE_REQUESTS" ("STATUS") 
  ;
