  --Table name: APP_USER 

  CREATE TABLE "APP_USER" 
   (	"USER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"PWD" VARCHAR2(40) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(20) DEFAULT USER, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(30) NOT NULL ENABLE, 
	"EMP_ID" NUMBER, 
	 PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "APP_USER_CON" UNIQUE ("USER_NAME", "PWD")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "APP_USER" ADD CONSTRAINT "FK_APPUSER_EMP" FOREIGN KEY ("EMP_ID")
	  REFERENCES "EMPLOYEES" ("EMP_ID") ENABLE;

--Table name: "DEPARTMENTS" 
  CREATE TABLE "DEPARTMENTS" 
   (	"DEPT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DEPT_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(30) NOT NULL ENABLE, 
	 PRIMARY KEY ("DEPT_ID")
  USING INDEX  ENABLE
   ) ;
--Table name: "EMPLOYEES" 
  CREATE TABLE "EMPLOYEES" 
   (	"EMP_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"EMP_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(40) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(30) NOT NULL ENABLE, 
	"DEPT_ID" NUMBER NOT NULL ENABLE, 
	"MANAGER_ID" NUMBER, 
	"JOIN_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL ENABLE, 
	 CONSTRAINT "EMP_STATUS_IN" CHECK (STATUS IN('ACTIVE','INACTIVE','ON_LEAVE')) ENABLE, 
	 PRIMARY KEY ("EMP_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "EMPLOYEES" ADD CONSTRAINT "FK_DEPT_ID" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "DEPARTMENTS" ("DEPT_ID") ENABLE;

  CREATE INDEX "EMP_DEPT_IDX" ON "EMPLOYEES" ("DEPT_ID") 
  ;

--Table name: "LEAVE_AUDIT"
  CREATE TABLE "LEAVE_AUDIT" 
   (	"AUDIT_ID" NUMBER NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER NOT NULL ENABLE, 
	"OLD_STATUS" VARCHAR2(20), 
	"NEW_STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	"CHANGED_BY" NUMBER NOT NULL ENABLE, 
	"CHANGED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_AUDIT_ID" PRIMARY KEY ("AUDIT_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "LEAVE_AUDIT" ADD CONSTRAINT "FK_AUDIT_EMP_ID" FOREIGN KEY ("CHANGED_BY")
	  REFERENCES "EMPLOYEES" ("EMP_ID") ENABLE;
  ALTER TABLE "LEAVE_AUDIT" ADD CONSTRAINT "FK_REQUEST_ID" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "LEAVE_REQUESTS" ("REQUEST_ID") ENABLE;

  CREATE INDEX "REQID_AUDIT_IDX" ON "LEAVE_AUDIT" ("REQUEST_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "LTRG_LEAVE_REQUESTS_AUDIT" 
after
 update  on "LEAVE_AUDIT"
for each row
begin
    INSERT INTO LEAVE_AUDIT (
        REQUEST_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_DATE
    ) VALUES (
        :NEW.REQUEST_ID, :OLD.STATUS, :NEW.STATUS,
        PKG_LEAVE.G_CURRENT_MANAGER_ID, SYSDATE
    );
end;
/
ALTER TRIGGER "LTRG_LEAVE_REQUESTS_AUDIT" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_LEAVE_AUDIT_ID" 
BEFORE INSERT ON LEAVE_AUDIT
FOR EACH ROW
 WHEN (NEW.AUDIT_ID IS NULL) BEGIN
:NEW.AUDIT_ID := LEAVE_AUDIT_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "TRG_LEAVE_AUDIT_ID" ENABLE;

--Table name: "LEAVE_REQUESTS"
  CREATE TABLE "LEAVE_REQUESTS" 
   (	"REQUEST_ID" NUMBER, 
	"EMP_ID" NUMBER, 
	"TYPE_ID" NUMBER, 
	"FROM_DATE" DATE DEFAULT SYSDATE, 
	"TO_DATE" DATE, 
	"TOTAL_DAYS" NUMBER, 
	"REASON" VARCHAR2(1000), 
	"STATUS" VARCHAR2(30) DEFAULT 'PENDING', 
	"MANAGER_REMARK" VARCHAR2(1000), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("REQUEST_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "LEAVE_REQ_STATUS" CHECK (STATUS IN ('PENDING','APPROVED','REJECTED')) ENABLE
   ) ;

  ALTER TABLE "LEAVE_REQUESTS" ADD CONSTRAINT "FK_EMP_ID" FOREIGN KEY ("EMP_ID")
	  REFERENCES "EMPLOYEES" ("EMP_ID") ENABLE;
  ALTER TABLE "LEAVE_REQUESTS" ADD CONSTRAINT "FK_TYPE_ID" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "LEAVE_TYPES" ("TYPE_ID") ENABLE;

  CREATE INDEX "EMPID_LEAVE_IDX" ON "LEAVE_REQUESTS" ("EMP_ID") 
  ;

  CREATE INDEX "STATUS_LEAVE_IDX" ON "LEAVE_REQUESTS" ("STATUS") 
  ;

  CREATE INDEX "TYPEID_LEAVE_IDX" ON "LEAVE_REQUESTS" ("TYPE_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_LEAVE_REQUESTS_AUDIT" 
after
 update  OF STATUS ON "LEAVE_REQUESTS"
for each row
begin
    INSERT INTO LEAVE_AUDIT (
        REQUEST_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_DATE
    ) VALUES (
        :NEW.REQUEST_ID, :OLD.STATUS, :NEW.STATUS,
        PKG_LEAVE.G_CURRENT_MANAGER_ID, SYSDATE
    );
end;
/
ALTER TRIGGER "TRG_LEAVE_REQUESTS_AUDIT" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_LEAVE_REQUESTS_BI" 
before 
insert on "LEAVE_REQUESTS"
for each row
begin
    -- Auto-calculate total days (inclusive of both start and end date)
      :NEW.TOTAL_DAYS := (:NEW.TO_DATE - :NEW.FROM_DATE) + 1;

-- Auto-store created date if not already supplied
IF:NEW.CREATED_DATE  IS NULL THEN
:NEW.CREATED_DATE  := SYSDATE;
END IF;

end;
/
ALTER TRIGGER "TRG_LEAVE_REQUESTS_BI" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_LEAVE_REQUESTS_ID" 
BEFORE INSERT ON LEAVE_REQUESTS
FOR EACH ROW
 WHEN (NEW.REQUEST_ID IS NULL) BEGIN
    :NEW.REQUEST_ID := LEAVE_REQUESTS_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "TRG_LEAVE_REQUESTS_ID" ENABLE;

--Table name: "LEAVE_TYPES"
  CREATE TABLE "LEAVE_TYPES" 
   (	"TYPE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TYPE_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"MAX_DAYS" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("TYPE_ID")
  USING INDEX  ENABLE
   ) ;